version: '3'
services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: p1c4d1nh0
    ports:
      - 27017:27017

  mysql:
    image: mysql
    container_name: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: server

  products-ms:
    image: products-ms
    build:
      context: products-ms
      dockerfile: Dockerfile
    depends_on:
      - mongo
    environment:
      NODE_ENV: DOCKER
      NODE_PORT: '3002'
    ports:
      - 3002:3002

  shopping-cart-ms:
    image: shopping-cart-ms
    build:
      context: shopping-cart-ms
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - products-ms
    environment:
      NODE_ENV: DOCKER
      NODE_PORT: '3001'
    ports:
      - 3001:3001

  api:
    image: api
    build:
      context: api
      dockerfile: Dockerfile
    depends_on:
      - shopping-cart-ms
      - mysql
    environment:
      NODE_ENV: DOCKER
      NODE_PORT: '3000'
    ports:
      - 3000:3000
